### Local Server API

POST http://localhost:7001/api/v1/verification/signature
Content-Type: application/json

{
  "account":"string",
  "signature":"string"
}

### Production API

POST http://localhost:8080/api/v1/verification/signature
Content-Type: application/json

{
  "account":"string",
  "signature":"string"
}